Improves OOP exercise instructions
cbfacademy/intro-to-java-course pull request #33
Opened 2024-06-12 17:24 UTC by Genyus

- Adds test exclusion instructions for shapes and accounts exercises
- Adds instructions to run application code
- Improves heading labels

2024-06-12 21:59 UTC, tanyapowell approved these changes

2024-06-18 08:16 UTC, tanyapowell requested changes

2024-06-18 08:16 UTC, tanyapowell commented on exercises/object-oriented-programming/README.md
> +If you want to experiment with the provided application in the App.java file, you can run a command in this format `./mvnw -q --projects [project name] clean compile exec:java -Dexec.mainClass=[packa
Is this command different on Windows?

2024-06-18 08:16 UTC, tanyapowell commented on exercises/algorithms/search/src/main/java/com/cbfacademy/search/Search.java
> +     *                    rted)
This formatting is a bit weird

2024-06-18 17:22 UTC, Genyus commented on exercises/object-oriented-programming/README.md
> +If you want to experiment with the provided application in the App.java file, you can run a command in this format `./mvnw -q --projects [project name] clean compile exec:java -Dexec.mainClass=[packa
Not to my knowledge

2024-06-19 18:15 UTC, tanyapowell approved these changes

2024-06-19 18:20 UTC, Genyus commented on exercises/object-oriented-programming/README.md
> -```bat
Eventually yes, although I'd say it's low priority. We've been pushing Windows students to use the Git terminal, which uses the same Linux-style commands, but it's not formalised, so we should clearly define our policy in this area first

2024-06-19 18:20 UTC, merged